version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - '2181:2181'

  kafka:
    image: wurstmeister/kafka:2.11-1.1.0
    ports:
      - '9092:9092'
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: 'test-topic:1:1'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  mongo:
    container_name: mongo_db
    image: mongo:3.6.21
    ports:
      - '27017:27017'
    volumes:
      - ./docker/mongodb:/data/db
    networks:
      - default

  redis:
    image: redis:3.2
    container_name: redis
    volumes:
      - ./db/storage/cache:/data:cached
    command: redis-server
    ports:
      - 6379:6379
    networks:
      - default
